import Footer from "./footer";
import Header from "./header";
import Head from 'next/head'
export default function Layout({ children }) {

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <div className="bg-primary">
        {children}
      </div>
      <Footer />
    </>
  )
}